meta_product_name: "KITWE"
meta_title: "KITWE - Everything Everyone we keep in touch with"
meta_description: "KITWE - Everything Everyone we keep in touch with"
meta_image: "components/og-image-menu.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
